// Curated lucide-react icon set used across the Phase 1 UI polish.
// Centralised so icon swaps are one-line edits instead of grep-and-replace.
export {
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  Search,
  SearchX,
  RefreshCw,
  HelpCircle,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  MinusCircle,
  Info,
  Mail,
  Globe,
  Download,
  MessageSquare,
  Sparkles,
  LogOut,
  Menu,
  X,
  Copy,
  ExternalLink,
  Loader2,
  Upload,
  Image as ImageIcon,
  UserCircle2,
  ScanSearch,
} from "lucide-react";
